<a href="https://colab.research.google.com/github/Udaykiran06-art/NUMPY-MINI-PROJECT/blob/main/NUMPY_MINI_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def main():
    # Step 1: Store temperatures for 7 days (°C)
    temperatures = np.array([22.5, 24.0, 19.8, 21.4, 25.1, 23.3, 20.0])

    # Step 2: Find the hottest and coldest temperatures
    max_temp = np.max(temperatures)
    min_temp = np.min(temperatures)

    print("Hottest temperature of the week:", max_temp, "°C")
    print("Coldest temperature of the week:", min_temp, "°C")

    # Step 3: Calculate average temperature
    avg_temp = np.mean(temperatures)
    print("Average temperature of the week:", round(avg_temp, 2), "°C")

    # Step 4: Find days with above average temperature
    above_avg = temperatures > avg_temp
    above_avg_days = temperatures[above_avg]

    print("Temperatures above average:", above_avg_days)
    print("Number of days above average:", len(above_avg_days))


    # Step 5: Identify hottest and coldest days (index + 1 for day number)
    hottest_day = np.where(temperatures == max_temp)[0][0] + 1
    coldest_day = np.where(temperatures == min_temp)[0][0] + 1

    # Step 6: Display results
    print("=== Temperature Data Analyzer ===")
    print("Temperatures (°C):", temperatures)
    print(f"Hottest Temperature: {max_temp:.1f}°C (Day {hottest_day})")
    print(f"Coldest Temperature: {min_temp:.1f}°C (Day {coldest_day})")
    print(f"Average Temperature: {avg_temp:.1f}°C")
    print(f"Number of Days Above Average: (len(above_avg_days))")
    print("Temperatures Above Average:", above_avg)

if __name__ == "__main__":
    main()


Hottest temperature of the week: 25.1 °C
Coldest temperature of the week: 19.8 °C
Average temperature of the week: 22.3 °C
Temperatures above average: [22.5 24.  25.1 23.3]
Number of days above average: 4
=== Temperature Data Analyzer ===
Temperatures (°C): [22.5 24.  19.8 21.4 25.1 23.3 20. ]
Hottest Temperature: 25.1°C (Day 5)
Coldest Temperature: 19.8°C (Day 3)
Average Temperature: 22.3°C
Number of Days Above Average: (len(above_avg_days))
Temperatures Above Average: [ True  True False False  True  True False]


In [ ]:
#Analyze marks of students in different subjects using numpy arrays
#Marks of 5 students in 3 subjects : [math, science, english]
import numpy as np
marks = np.array([[98,99,97],#student1
                 [88,89,87],#student2
                  [78,100,85],#student3
                  [84,83,81],#student4
                  [81,80,100] #student5
                  ])
print("Marks matrix:\\n,marks")

#calculate average marks per student and per subject
avg_marks_per_student = np.array(np.mean(marks,axis=1))
print("Average marks per student:\\n,avg_marks_per_student")

avg_marks_per_subject = np.array(np.mean(marks,axis=0))
print("Average marks per subject:\\n,avg_marks_per_subject")

#find toppers in each subjet
topper_indices = np.argmax(marks,axis=0)
subjects = ["Math", "Science", "English"]
for i,subject in enumerate(subjects):
    topper_index = topper_indices[i]
    topper_name = f"Student{topper_index+1}"
    print(f"Topper in {subject:},{topper_name}")

#Calculate Standard Deviation per Subject
std_dev_per_subject = np.std(marks,axis=0)
print("Standard Deviation Per Subject",std_dev_per_subject)


print("\n--- Summary ---")
print("Marks:\n", marks)
print("Average per student:", avg_marks_per_student)
print("Average per subject:", avg_marks_per_subject)
print("Standard deviation per subject:", std_dev_per_subject)






Marks matrix:\n,marks
Average marks per student:\n,avg_marks_per_student
Average marks per subject:\n,avg_marks_per_subject
Topper in Math,Student1
Topper in Science,Student3
Topper in English,Student5
Standard Deviation Per Subject [6.93974063 8.13387976 7.26636085]

--- Summary ---
Marks:
 [[ 98  99  97]
 [ 88  89  87]
 [ 78 100  85]
 [ 84  83  81]
 [ 81  80 100]]
Average per student: [98.         88.         87.66666667 82.66666667 87.        ]
Average per subject: [85.8 90.2 90. ]
Standard deviation per subject: [6.93974063 8.13387976 7.26636085]
